const fs=require('fs');const path=require('path');const {Document,Packer,Paragraph,TextRun,HeadingLevel,Footer,PageNumber,AlignmentType}=require('C:/Users/STALYN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/docx');
const dir=path.resolve('revision_coherencia/entregables');const obs=JSON.parse(fs.readFileSync(path.join(dir,'observaciones.json'),'utf8'));
const body=[];const para=(text,opts={})=>new Paragraph({spacing:{after:100},...opts,children:[new TextRun(text)]});
body.push(para('ENUS 2026',{heading:HeadingLevel.TITLE}),para('Observaciones a los formularios y matriz de indicadores V07',{heading:HeadingLevel.SUBTITLE}),para('Revisión del 5 de octubre de 2026'));
body.push(para('Alcance de la revisión',{heading:HeadingLevel.HEADING_1}),para('Se presentan 26 observaciones: 23 documentadas en la matriz vigente y 3 derivadas del contraste con el documento técnico. Cada punto identifica ubicación, problema, impacto, indicadores y acción propuesta. Los formularios fuente no se modificaron.'));
body.push(para('Fuentes',{heading:HeadingLevel.HEADING_2}),para('Cuestionario: ENUS_Formato_por_Modulos_CartaDerechos_V07 17092026.xlsx.'),para('Indicadores: Matriz_de_indicadores_-_Fichas_tecnicas_ENUS_V07_30092026.xlsx. Ambos archivos están en 00_Cuestionario/V1.'));
body.push(para('Prioridades y seguimiento',{heading:HeadingLevel.HEADING_2}),para('7 observaciones de prioridad alta, 10 media, 8 baja y 1 resuelta en la fuente. Las prioridades de los puntos 1–23 proceden de la matriz; las de 24–26 son propuestas de esta revisión. El Excel complementario permite registrar responsable, compromiso, respuesta y evidencia de cierre.'));
body.push(para('Decisiones prioritarias',{heading:HeadingLevel.HEADING_2}),para('Resolver la relación entre el periodo anual del cuestionario y el marco de seis meses, y armonizar la preselección por perfil con la asignación de módulos. En paralelo, corregir rutas del gestor, aplicabilidad de preguntas, correspondencia de códigos y versiones. Las acciones propuestas deben ser validadas por el equipo técnico.'));
for(const o of obs){body.push(para(`${String(o.id).padStart(2,'0')}. ${o.location}`,{heading:HeadingLevel.HEADING_1,keepNext:true}));body.push(para(`Prioridad: ${o.priority} | Estado: ${o.status}`,{keepNext:true}));for(const [label,key] of [['Origen','origin'],['Observación','finding'],['Impacto','impact'],['Indicadores afectados','indicators'],['Acción propuesta','action'],['Fuente y ubicación','source']]){body.push(new Paragraph({spacing:{after:90},children:[new TextRun({text:label+': ',bold:true}),new TextRun(o[key])]}));}}
const doc=new Document({styles:{default:{document:{run:{font:'Arial',size:21},paragraph:{spacing:{line:260}}}},heading1:{run:{font:'Arial',size:25,bold:true,color:'1F4E79'},paragraph:{spacing:{before:220,after:100}}},heading2:{run:{font:'Arial',size:23,bold:true,color:'1F4E79'}}},sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:1134,bottom:1134,left:1134,right:1134}}},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.RIGHT,children:[new TextRun('ENUS V07 · '),new TextRun({children:[PageNumber.CURRENT]})]})]})},children:body}]});
Packer.toBuffer(doc).then(b=>fs.writeFileSync(path.join(dir,'Observaciones_formularios_ENUS_V07.docx'),b));
