from pathlib import Path
import json,collections
from openpyxl import load_workbook
import xlsxwriter
root=Path.cwd();out=root/'revision_coherencia/entregables';out.mkdir(exist_ok=True)
p=next((root/'00_Cuestionario/V1').glob('Matriz*.xlsx'));w=load_workbook(p,data_only=True);sh=w['Hallazgos del instrumento'];obs=[]
for rn,row in enumerate(sh.values,1):
 if not isinstance(row[0],(int,float)):continue
 priority=str(row[6]);obs.append(dict(id=int(row[0]),location=str(row[1]),finding=str(row[2]),impact=str(row[3]),indicators=str(row[4]),action=str(row[5]),priority='No aplica' if priority=='Resuelto' else priority,status='Resuelto en fuente' if priority=='Resuelto' else 'Pendiente',origin='Matriz V07: hallazgo documentado',source=p.name+' | Hallazgos del instrumento | fila '+str(rn)))
extra=[('Periodo del cuestionario y marco','Las preguntas V07 usan el último año; el diseño técnico mantiene atenciones registradas en los últimos seis meses.','Los universos y periodos pueden no coincidir; afecta interpretación y calibración.','Transversales y por módulo','Definir y documentar la relación entre ventana de elegibilidad, periodo de las preguntas y universo anual. No cambiar automáticamente todos los periodos.'),('Perfil de aplicación y asignación de módulos','El Índice del formulario describe preselección por perfil, incluido no usuario; el documento técnico plantea asignación aleatoria dentro del actor.','Puede asignarse contenido no aplicable; las probabilidades y los universos de los pesos dependen de la decisión.','Todos los modelos de módulo','Resolver la elegibilidad por módulo y el universo de EPS 1. Recalcular probabilidades y revisar los totales de calibración si cambia el conjunto asignable.'),('Identificación de versión y documentación del prototipo','Los nombres de los archivos son V07, algunos encabezados internos dicen V04 y las capturas de ClicSalud muestran una estructura anterior.','Dificulta identificar la especificación que debe implementar y auditar el equipo.','Todos (trazabilidad)','Unificar identificadores de versión y fechas. Actualizar las capturas después de implementar los textos y rutas aprobados.')]
for i,x in enumerate(extra,24):obs.append(dict(id=i,location=x[0],finding=x[1],impact=x[2],indicators=x[3],action=x[4],priority='Alta' if i<26 else 'Media',status='Requiere decisión',origin='Contraste con documento técnico',source='Formulario V07 (Índice y módulos) / capítulos 06, 13 y 18'))
(out/'observaciones.json').write_text(json.dumps(obs,ensure_ascii=False,indent=2),encoding='utf8')
b=xlsxwriter.Workbook(str(out/'Observaciones_formularios_ENUS_V07.xlsx'));wrap=b.add_format({'font_name':'Arial','font_size':10,'text_wrap':True,'valign':'top'});hdr=b.add_format({'font_name':'Arial','bold':True,'bg_color':'#1F4E79','font_color':'white','text_wrap':True});s=b.add_worksheet('Observaciones');headers=['ID','Origen','Ubicación / módulo','Observación','Impacto','Indicadores afectados','Acción propuesta','Prioridad','Estado','Fuente y ubicación','Responsable','Fecha compromiso','Respuesta del equipo','Evidencia de cierre'];s.write_row(0,0,headers,hdr)
for i,o in enumerate(obs,1):s.write_row(i,0,[o['id'],o['origin'],o['location'],o['finding'],o['impact'],o['indicators'],o['action'],o['priority'],o['status'],o['source'],'','','',''],wrap);s.set_row(i,115)
s.freeze_panes(1,3);s.autofilter(0,0,len(obs),13);s.set_column(0,0,6);s.set_column(1,2,30);s.set_column(3,4,55);s.set_column(5,5,30);s.set_column(6,6,60);s.set_column(7,8,22);s.set_column(9,9,45);s.set_column(10,13,28);s.data_validation(1,8,len(obs),8,{'validate':'list','source':['Pendiente','Requiere decisión','En revisión','En ajuste','Resuelto en fuente','Cerrado']});s.data_validation(1,7,len(obs),7,{'validate':'list','source':['Alta','Media','Baja','No aplica']})
s.set_landscape();s.fit_to_pages(1,0);s.repeat_rows(0);s.hide_gridlines(2)
r=b.add_worksheet('Resumen');r.set_column(0,0,48);r.set_column(1,1,18);r.write_row(0,0,['Control','Cantidad'],hdr)
counts=collections.Counter(o['priority'] for o in obs)
r.write(1,0,'Total de observaciones');r.write_formula(1,1,'=COUNTA(Observaciones!A2:A27)',None,len(obs))
for i,label in enumerate(['Alta','Media','Baja','No aplica'],2):r.write(i,0,label);r.write_formula(i,1,f'=COUNTIF(Observaciones!H2:H27,A{i+1})',None,counts[label])
r.write(7,0,'Resuelto en fuente');r.write_formula(7,1,'=COUNTIF(Observaciones!I2:I27,A8)',None,1)
n=b.add_worksheet('Guía');n.set_column(0,0,32);n.set_column(1,1,110)
notes=[('Objeto','Revisión punto por punto de los formularios y matriz V07. Fecha: 5 de octubre de 2026.'),('Alcance','23 hallazgos de la matriz fuente y 3 observaciones adicionales por contraste con el documento técnico.'),('Uso','Filtre por prioridad, módulo o estado. Complete responsable, fecha, respuesta y evidencia. Los archivos V1 no se modificaron.'),('Prioridad','1–23: prioridad documentada en la matriz; 24–26: prioridad propuesta en la revisión. El punto 23 está resuelto en la fuente.'),('Cierre','La acción propuesta requiere revisión del equipo; no significa que el formulario ya esté corregido. Registre evidencia antes de marcar Cerrado.'),('Fuentes',p.name+'; ENUS_Formato_por_Modulos_CartaDerechos_V07 17092026.xlsx')]
for i,row in enumerate(notes):n.write_row(i,0,row,wrap);n.set_row(i,45)
b.close();v=load_workbook(out/'Observaciones_formularios_ENUS_V07.xlsx',data_only=True);assert v['Resumen']['B2'].value==26;assert not any(c.data_type=='e' for sh in v for row in sh for c in row)
print('26 observaciones; Excel verificado',dict(counts))
